export declare const MakerDaoMetric: {
    makerdao_action_deposits: import("../utils").Node<Studio.Metric, "makerdao_action_deposits">;
    makerdao_action_liquidations: import("../utils").Node<Studio.Metric, "makerdao_action_liquidations">;
    makerdao_action_new_debt: import("../utils").Node<Studio.Metric, "makerdao_action_new_debt">;
    dai_created: import("../utils").Node<Studio.Metric, "dai_created">;
    makerdao_action_repayments: import("../utils").Node<Studio.Metric, "makerdao_action_repayments">;
    dai_repaid: import("../utils").Node<Studio.Metric, "dai_repaid">;
    total_dai_created: import("../utils").Node<Studio.Metric, "total_dai_created">;
    makerdao_action_deposits_usd: import("../utils").Node<Studio.Metric, "makerdao_action_deposits_usd">;
    makerdao_action_liquidations_usd: import("../utils").Node<Studio.Metric, "makerdao_action_liquidations_usd">;
    makerdao_action_new_debt_usd: import("../utils").Node<Studio.Metric, "makerdao_action_new_debt_usd">;
    makerdao_action_repayments_usd: import("../utils").Node<Studio.Metric, "makerdao_action_repayments_usd">;
    makerdao_total_deposits_usd: import("../utils").Node<Studio.Metric, "makerdao_total_deposits_usd">;
    makerdao_total_liquidations_usd: import("../utils").Node<Studio.Metric, "makerdao_total_liquidations_usd">;
    makerdao_total_new_debt_usd: import("../utils").Node<Studio.Metric, "makerdao_total_new_debt_usd">;
    makerdao_total_repayments_usd: import("../utils").Node<Studio.Metric, "makerdao_total_repayments_usd">;
    makerdao_total_supplied: import("../utils").Node<Studio.Metric, "makerdao_total_supplied">;
    makerdao_total_supplied_usd: import("../utils").Node<Studio.Metric, "makerdao_total_supplied_usd">;
    makerdao_total_borrowed: import("../utils").Node<Studio.Metric, "makerdao_total_borrowed">;
    makerdao_total_borrowed_usd: import("../utils").Node<Studio.Metric, "makerdao_total_borrowed_usd">;
    makerdao_protocol_total_supplied_usd: import("../utils").Node<Studio.Metric, "makerdao_protocol_total_supplied_usd">;
    makerdao_protocol_total_borrowed_usd: import("../utils").Node<Studio.Metric, "makerdao_protocol_total_borrowed_usd">;
    mcd_collat_ratio: import("../utils").Node<Studio.Metric, "mcd_collat_ratio">;
    mcd_stability_fee: import("../utils").Node<Studio.Metric, "mcd_stability_fee">;
    mcd_dsr: import("../utils").Node<Studio.Metric, "mcd_dsr">;
    makerdao_active_addresses: import("../utils").Node<Studio.Metric, "makerdao_active_addresses">;
};
export declare const MakerDaoDsrMetric: {
    makerdao_dsr_deposits: import("../utils").Node<Studio.Metric, "makerdao_dsr_deposits">;
    makerdao_dsr_withdrawals: import("../utils").Node<Studio.Metric, "makerdao_dsr_withdrawals">;
    makerdao_dsr_total_supplied: import("../utils").Node<Studio.Metric, "makerdao_dsr_total_supplied">;
};
